name: Security workflow
on: ["push"]

jobs:
  Secrets-Scanning:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install and Run Gitleaks 
        run: |
          wget -qO gitleaks.tar.gz https://github.com/gitleaks/gitleaks/releases/download/v8.30.0/gitleaks_8.30.0_linux_x64.tar.gz
          tar -xvf gitleaks.tar.gz
          chmod +x gitleaks
          mv gitleaks /usr/local/bin/gitleaks
          gitleaks detect -s . -f json -r secrets-scanning-results.json
      - name: Upload Secrets scanning Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: secrets-scanning-results
          path: secrets-scanning-results.json
