name: Security workflow
on: ["push"]

jobs:
  Secrets-Scanning:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Print message
        run: echo "Hellow world"
      - name: List directory
        run: ls -al
